// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package store

import (
	"context"
)

const platformHealth = `-- name: PlatformHealth :one
SELECT 1::integer AS result
`

func (q *Queries) PlatformHealth(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, platformHealth)
	var result int32
	err := row.Scan(&result)
	return result, err
}
