// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID          int64              `json:"id"`
	ActorUserID pgtype.UUID        `json:"actor_user_id"`
	Action      string             `json:"action"`
	TargetType  string             `json:"target_type"`
	TargetID    string             `json:"target_id"`
	Reason      string             `json:"reason"`
	BeforeHash  *string            `json:"before_hash"`
	AfterHash   *string            `json:"after_hash"`
	RequestID   string             `json:"request_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Event struct {
	ID                  pgtype.UUID        `json:"id"`
	Slug                string             `json:"slug"`
	EventType           string             `json:"event_type"`
	Lifecycle           string             `json:"lifecycle"`
	Priority            string             `json:"priority"`
	Confidence          string             `json:"confidence"`
	LocationName        string             `json:"location_name"`
	Location            []byte             `json:"location"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	VerifiedAt          pgtype.Timestamptz `json:"verified_at"`
	PublishedRevisionID pgtype.UUID        `json:"published_revision_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type EventObservation struct {
	EventID       pgtype.UUID        `json:"event_id"`
	ObservationID pgtype.UUID        `json:"observation_id"`
	LinkedAt      pgtype.Timestamptz `json:"linked_at"`
}

type EventRevision struct {
	ID          pgtype.UUID        `json:"id"`
	EventID     pgtype.UUID        `json:"event_id"`
	Revision    int32              `json:"revision"`
	Title       string             `json:"title"`
	Summary     string             `json:"summary"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

type Job struct {
	ID               pgtype.UUID        `json:"id"`
	Type             string             `json:"type"`
	IdempotencyKey   string             `json:"idempotency_key"`
	State            string             `json:"state"`
	Payload          []byte             `json:"payload"`
	Attempt          int32              `json:"attempt"`
	MaxAttempts      int32              `json:"max_attempts"`
	AvailableAt      pgtype.Timestamptz `json:"available_at"`
	LeaseOwner       *string            `json:"lease_owner"`
	LeaseExpiresAt   pgtype.Timestamptz `json:"lease_expires_at"`
	LastErrorCode    *string            `json:"last_error_code"`
	LastErrorMessage *string            `json:"last_error_message"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
}

type Observation struct {
	ID          pgtype.UUID        `json:"id"`
	SourceID    pgtype.UUID        `json:"source_id"`
	ExternalID  string             `json:"external_id"`
	Version     int32              `json:"version"`
	ContentHash string             `json:"content_hash"`
	ObservedAt  pgtype.Timestamptz `json:"observed_at"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	Location    interface{}        `json:"location"`
	Payload     []byte             `json:"payload"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type SchemaMetadatum struct {
	Singleton                bool               `json:"singleton"`
	ApplicationVersion       string             `json:"application_version"`
	MinimumCompatibleVersion string             `json:"minimum_compatible_version"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  []byte             `json:"token_hash"`
	CsrfHash   []byte             `json:"csrf_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Source struct {
	ID            pgtype.UUID        `json:"id"`
	Key           string             `json:"key"`
	Name          string             `json:"name"`
	HomepageUrl   string             `json:"homepage_url"`
	Enabled       bool               `json:"enabled"`
	LastSuccessAt pgtype.Timestamptz `json:"last_success_at"`
	LastErrorAt   pgtype.Timestamptz `json:"last_error_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type TimelineEntry struct {
	ID            pgtype.UUID        `json:"id"`
	EventID       pgtype.UUID        `json:"event_id"`
	ObservationID pgtype.UUID        `json:"observation_id"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	Title         string             `json:"title"`
	Body          string             `json:"body"`
	Published     bool               `json:"published"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	DisplayName  string             `json:"display_name"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	Active       bool               `json:"active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
